/**
 * Shared, evidence-reviewed names used by both the legacy repair pipeline and
 * the unified evidence workflow. This catalog is a deterministic fallback;
 * unknown names still have to be resolved from external evidence rather than
 * guessed.
 */
export const KNOWN_PRODUCT_CANONICAL_FORMS = new Map([
    [ "3D IC", "3D IC 三维集成电路（Three-Dimensional Integrated Circuit）" ],
    [ "3D堆叠ML加速器", "三维堆叠机器学习加速器（3D-Stacked Machine Learning Accelerator）" ],
    [ "ACM Transactions on Design Automation of Electronic Systems", "计算机学会设计自动化电子系统汇刊（ACM Transactions on Design Automation of Electronic Systems）" ],
    [ "ACM Trans. Design Autom. Electr. Syst.", "计算机学会设计自动化电子系统汇刊（ACM Transactions on Design Automation of Electronic Systems）" ],
    [ "AI", "AI 人工智能（Artificial Intelligence）" ],
    [ "ACM", "ACM 美国计算机协会（Association for Computing Machinery）" ],
    [ "Apple", "苹果公司（Apple）" ],
    [ "Dean's Professor", "院长讲席教授（Dean's Professor）" ],
    [ "Georgia Tech", "佐治亚理工学院（Georgia Institute of Technology）" ],
    [ "Motorola Solutions Foundation Professor", "摩托罗拉解决方案基金会教授（Motorola Solutions Foundation Professor）" ],
    [ "ASIC", "ASIC 专用集成电路（Application-Specific Integrated Circuit）" ],
    [ "CCF", "CCF 中国计算机学会（China Computer Federation）" ],
    [ "CPU", "CPU 中央处理器（Central Processing Unit）" ],
    [ "CXL.io", "CXL.io 输入/输出协议" ],
    [ "CXL", "CXL 计算快速链路（Compute Express Link）" ],
    [ "DMA", "DMA 直接内存访问（Direct Memory Access）" ],
    [ "DOM", "DOM 文档对象模型（Document Object Model）" ],
    [ "I/O", "I/O 输入/输出（Input/Output）" ],
    [ "DAC", "DAC 设计自动化会议（Design Automation Conference）" ],
    [ "DAX", "DAX 直接访问（Direct Access）" ],
    [ "3D-MAPS", "3D-MAPS 三维大规模并行处理器与堆叠内存（3D Massively Parallel Processor with Stacked Memory）" ],
    [ "DBLP", "dblp 计算机科学书目服务（dblp computer science bibliography）" ],
    [ "DOI", "DOI 数字对象标识符（Digital Object Identifier）" ],
    [ "DRAM", "DRAM 动态随机存取存储器（Dynamic Random-Access Memory）" ],
    [ "dB", "dB 分贝（Decibel）" ],
    [ "DRC", "DRC 设计规则检查（Design Rule Check）" ],
    [ "EDA", "EDA 电子设计自动化（Electronic Design Automation）" ],
    [ "GPR", "GPR 高斯过程回归（Gaussian Process Regression）" ],
    [ "BFGS", "BFGS 布罗伊登—弗莱彻—戈德法布—香农算法（Broyden-Fletcher-Goldfarb-Shanno Algorithm）" ],
    [ "L-BFGS", "L-BFGS 有限内存布罗伊登—弗莱彻—戈德法布—香农算法（Limited-Memory Broyden-Fletcher-Goldfarb-Shanno）" ],
    [ "FPGA", "FPGA 现场可编程门阵列（Field-Programmable Gate Array）" ],
    [ "GPU", "GPU 图形处理器（Graphics Processing Unit）" ],
    [ "HBM", "HBM 高带宽存储器（High Bandwidth Memory）" ],
    [ "HDL", "HDL 硬件描述语言（Hardware Description Language）" ],
    [ "VHDL", "VHDL 超高速集成电路硬件描述语言（VHSIC Hardware Description Language）" ],
    [ "IEEE Access", "电气电子工程师学会开放获取期刊（IEEE Access）" ],
    [ "IEEE", "IEEE 电气电子工程师学会（Institute of Electrical and Electronics Engineers）" ],
    [ "ICCAD", "ICCAD 计算机辅助设计国际会议（International Conference on Computer-Aided Design）" ],
    [ "ISLPED", "ISLPED 国际低功耗电子与设计研讨会（International Symposium on Low Power Electronics and Design）" ],
    [ "ISPD", "ISPD 物理设计国际研讨会（International Symposium on Physical Design）" ],
    [ "LVS", "LVS 版图与原理图一致性检查（Layout Versus Schematic）" ],
    [ "ML", "ML 机器学习（Machine Learning）" ],
    [ "MOL", "MOL 中段制程（Middle of Line）" ],
    [ "PCR", "PCR 聚合酶链式反应（Polymerase Chain Reaction）" ],
    [ "p-value", "p 值（p-value）" ],
    [ "DNA", "DNA 脱氧核糖核酸（Deoxyribonucleic Acid）" ],
    [ "mRNA", "mRNA 信使核糖核酸（Messenger Ribonucleic Acid）" ],
    [ "RNA", "RNA 核糖核酸（Ribonucleic Acid）" ],
    [ "GDPR", "GDPR 通用数据保护条例（General Data Protection Regulation）" ],
    [ "P/E", "P/E 市盈率（Price-to-Earnings Ratio）" ],
    [ "API", "API 应用程序编程接口（Application Programming Interface）" ],
    [ "ACID", "ACID 原子性、一致性、隔离性与持久性（Atomicity, Consistency, Isolation, and Durability）" ],
    [ "AEAD", "AEAD 带关联数据的认证加密（Authenticated Encryption with Associated Data）" ],
    [ "CAD", "CAD 计算机辅助设计（Computer-Aided Design）" ],
    [ "CBT", "CBT 认知行为疗法（Cognitive Behavioral Therapy）" ],
    [ "CFD", "CFD 计算流体力学（Computational Fluid Dynamics）" ],
    [ "CNN", "CNN 卷积神经网络（Convolutional Neural Network）" ],
    [ "CSRF", "CSRF 跨站请求伪造（Cross-Site Request Forgery）" ],
    [ "CT", "CT 计算机断层扫描（Computed Tomography）" ],
    [ "ECG", "ECG 心电图（Electrocardiogram）" ],
    [ "ETL", "ETL 抽取、转换与加载（Extract, Transform, and Load）" ],
    [ "FEA", "FEA 有限元分析（Finite Element Analysis）" ],
    [ "Fellow", "会士（Fellow）" ],
    [ "FFT", "FFT 快速傅里叶变换（Fast Fourier Transform）" ],
    [ "DFT", "DFT 离散傅里叶变换（Discrete Fourier Transform）" ],
    [ "GIS", "GIS 地理信息系统（Geographic Information System）" ],
    [ "GPS", "GPS 全球定位系统（Global Positioning System）" ],
    [ "HTTP", "HTTP 超文本传输协议（Hypertext Transfer Protocol）" ],
    [ "IP", "IP 网际协议（Internet Protocol）" ],
    [ "HTTPS", "HTTPS 超文本传输安全协议（Hypertext Transfer Protocol Secure）" ],
    [ "ECDHE", "ECDHE 临时椭圆曲线迪菲—赫尔曼密钥交换（Ephemeral Elliptic Curve Diffie-Hellman）" ],
    [ "ClientHello", "客户端问候消息（ClientHello）" ],
    [ "ServerHello", "服务器问候消息（ServerHello）" ],
    [ "LLM", "LLM 大语言模型（Large Language Model）" ],
    [ "MFA", "MFA 多因素身份验证（Multi-Factor Authentication）" ],
    [ "MIDI", "MIDI 乐器数字接口（Musical Instrument Digital Interface）" ],
    [ "MPC", "MPC 模型预测控制（Model Predictive Control）" ],
    [ "MRI", "MRI 磁共振成像（Magnetic Resonance Imaging）" ],
    [ "NMR", "NMR 核磁共振（Nuclear Magnetic Resonance）" ],
    [ "NUMA", "NUMA 非一致性内存访问（Non-Uniform Memory Access）" ],
    [ "OLTP", "OLTP 联机事务处理（Online Transaction Processing）" ],
    [ "PID", "PID 比例—积分—微分（Proportional-Integral-Derivative）" ],
    [ "RAG", "RAG 检索增强生成（Retrieval-Augmented Generation）" ],
    [ "RCT", "RCT 随机对照试验（Randomized Controlled Trial）" ],
    [ "RFC", "RFC 征求意见稿（Request for Comments）" ],
    [ "R0", "R0 基本再生数（Basic Reproduction Number）" ],
    [ "SQL", "SQL 结构化查询语言（Structured Query Language）" ],
    [ "SVD", "SVD 奇异值分解（Singular Value Decomposition）" ],
    [ "TESS", "TESS 凌日系外行星巡天卫星（Transiting Exoplanet Survey Satellite）" ],
    [ "UDP", "UDP 用户数据报协议（User Datagram Protocol）" ],
    [ "URL", "URL 统一资源定位符（Uniform Resource Locator）" ],
    [ "UUID", "UUID 通用唯一标识符（Universally Unique Identifier）" ],
    [ "WAL", "WAL 预写日志（Write-Ahead Logging）" ],
    [ "XSS", "XSS 跨站脚本（Cross-Site Scripting）" ],
    [ "REST", "REST 表述性状态转移（Representational State Transfer）" ],
    [ "TLS", "TLS 传输层安全协议（Transport Layer Security）" ],
    [ "SSL", "SSL 安全套接层（Secure Sockets Layer）" ],
    [ "RAM", "RAM 随机存取存储器（Random Access Memory）" ],
    [ "dB", "dB 分贝（Decibel）" ],
    [ "morpheme", "语素（Morpheme）" ],
    [ "不可靠叙述者", "不可靠叙述者（Unreliable Narrator）" ],
    [ "丝绸之路", "丝绸之路（Silk Road）" ],
    [ "NoC", "NoC 片上网络（Network on Chip）" ],
    [ "NPU", "NPU 神经网络处理单元（Neural Processing Unit）" ],
    [ "ORCID", "ORCID 开放研究者与贡献者标识符（Open Researcher and Contributor ID）" ],
    [ "PDN", "PDN 电源分配网络（Power Delivery Network）" ],
    [ "PCIe", "PCIe 高速外设组件互连（Peripheral Component Interconnect Express）" ],
    [ "PPA", "PPA 功耗、性能与面积（Power, Performance, and Area）" ],
    [ "RTL", "RTL 寄存器传输级（Register-Transfer Level）" ],
    [ "SoC", "SoC 片上系统（System on Chip）" ],
    [ "SRAM", "SRAM 静态随机存取存储器（Static Random-Access Memory）" ],
    [ "STA", "STA 静态时序分析（Static Timing Analysis）" ],
    [ "TPU", "TPU 张量处理单元（Tensor Processing Unit）" ],
    [ "TSV", "TSV 硅通孔（Through-Silicon Via）" ],
    [ "Chiplet", "芯粒（Chiplet）" ],
    [ "Hold Time", "保持时间（Hold Time）" ],
    [ "Hybrid Bonding", "混合键合（Hybrid Bonding）" ],
    [ "IR Drop", "电阻压降（IR Drop）" ],
    [ "Interposer", "中介层（Interposer）" ],
    [ "Setup Time", "建立时间（Setup Time）" ],
    [ "电路划分", "电路划分（Circuit Partitioning）" ],
    [ "边可分性", "边可分性（Edge Separability）" ],
    [ "WARP", "应急网络服务（WARP）" ],
    [ "Cloudflare WARP", "网络连接产品（Cloudflare WARP）" ],
    [ "Hiddify", "代理客户端（Hiddify）" ],
    [ "Windows", "操作系统（Windows）" ]
]);

export const KNOWN_ENTITY_NAMING_NOTES = new Map([
    [
        "DBLP",
        "dblp 当前正式名称是“dblp computer science bibliography”；"
        + "“Digital Bibliography & Library Project”只是曾使用的反向缩略语，官方已经停用；"
        + "不得把任何历史解释写成当前英文全称"
    ]
]);
